/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author Mauricio
 */
public class FramePrincipal extends javax.swing.JFrame {

    private GestionProductos gestionProductos = new GestionProductos();
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelPortada = new javax.swing.JPanel();
        nombreLocalL = new javax.swing.JLabel();
        direccionLocalL = new javax.swing.JLabel();
        contactoLocalL = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        menuToolBaar = new javax.swing.JToolBar();
        gestionProductosB = new javax.swing.JButton();
        gestionInventarioB = new javax.swing.JButton();
        gestionLocalB = new javax.swing.JButton();
        pedidosB = new javax.swing.JButton();
        estadisticasB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        nombreLocalL.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        nombreLocalL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLocalL.setText("Nombre de local");

        direccionLocalL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        direccionLocalL.setText("Dirección");

        contactoLocalL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contactoLocalL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contactoLocalL.setText("Contacto");

        javax.swing.GroupLayout panelPortadaLayout = new javax.swing.GroupLayout(panelPortada);
        panelPortada.setLayout(panelPortadaLayout);
        panelPortadaLayout.setHorizontalGroup(
            panelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPortadaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreLocalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPortadaLayout.createSequentialGroup()
                        .addComponent(direccionLocalL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                        .addComponent(contactoLocalL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        panelPortadaLayout.setVerticalGroup(
            panelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPortadaLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(nombreLocalL, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(panelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionLocalL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactoLocalL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );

        panelPrincipal.add(panelPortada, java.awt.BorderLayout.CENTER);

        menuToolBaar.setRollover(true);
        menuToolBaar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        gestionProductosB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gestionProductosB.setText("Gestión de productos");
        gestionProductosB.setFocusable(false);
        gestionProductosB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionProductosB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gestionProductosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionProductosBActionPerformed(evt);
            }
        });
        menuToolBaar.add(gestionProductosB);

        gestionInventarioB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gestionInventarioB.setText("Gestión de inventario");
        gestionInventarioB.setFocusable(false);
        gestionInventarioB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionInventarioB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuToolBaar.add(gestionInventarioB);

        gestionLocalB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gestionLocalB.setText("Gestión del Local");
        gestionLocalB.setFocusable(false);
        gestionLocalB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionLocalB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuToolBaar.add(gestionLocalB);

        pedidosB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pedidosB.setText("Pedidos");
        pedidosB.setFocusable(false);
        pedidosB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pedidosB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuToolBaar.add(pedidosB);

        estadisticasB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        estadisticasB.setText("Estadísticas");
        estadisticasB.setFocusable(false);
        estadisticasB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        estadisticasB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuToolBaar.add(estadisticasB);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuToolBaar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuToolBaar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionProductosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionProductosBActionPerformed
        panelPrincipal.setVisible(false);
        panelPrincipal.removeAll();
        panelPrincipal.add(gestionProductos);
        panelPrincipal.setVisible(true);
    }//GEN-LAST:event_gestionProductosBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactoLocalL;
    private javax.swing.JLabel direccionLocalL;
    private javax.swing.JButton estadisticasB;
    private javax.swing.JButton gestionInventarioB;
    private javax.swing.JButton gestionLocalB;
    private javax.swing.JButton gestionProductosB;
    private javax.swing.JToolBar menuToolBaar;
    private javax.swing.JLabel nombreLocalL;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPortada;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton pedidosB;
    // End of variables declaration//GEN-END:variables
}
