/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarLogin;
import Entidad.Local;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class FramePrincipal extends javax.swing.JFrame {

    private GestionProductos gestionProductos = new GestionProductos();
    private GestionInventario gestionInventario = new GestionInventario();
    private GestionLocal gestionLocal = new GestionLocal();
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        administradorL = new javax.swing.JLabel();
        administradorTF = new javax.swing.JTextField();
        contraseniaL = new javax.swing.JLabel();
        contraseniaPF = new javax.swing.JPasswordField();
        ingresarB = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        menuToolBaar = new javax.swing.JToolBar();
        gestionProductosB = new javax.swing.JButton();
        gestionInventarioB = new javax.swing.JButton();
        gestionLocalB = new javax.swing.JButton();
        pedidosB = new javax.swing.JButton();
        estadisticasB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        administradorL.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        administradorL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        administradorL.setText("Administrador");

        contraseniaL.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        contraseniaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contraseniaL.setText("Contraseña");

        ingresarB.setText("Ingresar");
        ingresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contraseniaPF)
                    .addComponent(contraseniaL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(administradorTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(administradorL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingresarB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(administradorL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administradorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(contraseniaL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseniaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ingresarB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelLogin, java.awt.BorderLayout.CENTER);

        menuToolBaar.setRollover(true);
        menuToolBaar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        gestionProductosB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gestionProductosB.setText("Gestión de productos");
        gestionProductosB.setEnabled(false);
        gestionProductosB.setFocusable(false);
        gestionProductosB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionProductosB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gestionProductosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionProductosBActionPerformed(evt);
            }
        });
        menuToolBaar.add(gestionProductosB);

        gestionInventarioB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gestionInventarioB.setText("Gestión de inventario");
        gestionInventarioB.setEnabled(false);
        gestionInventarioB.setFocusable(false);
        gestionInventarioB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionInventarioB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gestionInventarioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionInventarioBActionPerformed(evt);
            }
        });
        menuToolBaar.add(gestionInventarioB);

        gestionLocalB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gestionLocalB.setText("Gestión del Local");
        gestionLocalB.setEnabled(false);
        gestionLocalB.setFocusable(false);
        gestionLocalB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionLocalB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gestionLocalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionLocalBActionPerformed(evt);
            }
        });
        menuToolBaar.add(gestionLocalB);

        pedidosB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pedidosB.setText("Pedidos");
        pedidosB.setEnabled(false);
        pedidosB.setFocusable(false);
        pedidosB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pedidosB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuToolBaar.add(pedidosB);

        estadisticasB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        estadisticasB.setText("Estadísticas");
        estadisticasB.setEnabled(false);
        estadisticasB.setFocusable(false);
        estadisticasB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        estadisticasB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuToolBaar.add(estadisticasB);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuToolBaar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuToolBaar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionProductosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionProductosBActionPerformed
        panelPrincipal.setVisible(false);
        panelPrincipal.removeAll();
        panelPrincipal.add(gestionProductos);
        panelPrincipal.setVisible(true);
    }//GEN-LAST:event_gestionProductosBActionPerformed

    private void gestionInventarioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionInventarioBActionPerformed
        panelPrincipal.setVisible(false);
        panelPrincipal.removeAll();
        panelPrincipal.add(gestionInventario);
        panelPrincipal.setVisible(true);
    }//GEN-LAST:event_gestionInventarioBActionPerformed

    private void ingresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBActionPerformed
        Local local = new Local();
        local.setNombreAdministrador(administradorTF.getText());
        local.setContraseña(String.copyValueOf(contraseniaPF.getPassword()));
        ValidarLogin validar = new ValidarLogin();
        String resultado = validar.verificarLogin(local);
        JOptionPane.showMessageDialog(this, resultado, "Información", JOptionPane.INFORMATION_MESSAGE);
        if(resultado.equals("Ingreso exitoso")){
            gestionProductosB.setEnabled(true);
            gestionInventarioB.setEnabled(true);
            gestionLocalB.setEnabled(true);
            panelPrincipal.setVisible(false);
            panelPrincipal.removeAll();
            panelPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_ingresarBActionPerformed

    private void gestionLocalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionLocalBActionPerformed
        panelPrincipal.setVisible(false);
        panelPrincipal.removeAll();
        panelPrincipal.add(gestionLocal);
        panelPrincipal.setVisible(true);
    }//GEN-LAST:event_gestionLocalBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administradorL;
    private javax.swing.JTextField administradorTF;
    private javax.swing.JLabel contraseniaL;
    private javax.swing.JPasswordField contraseniaPF;
    private javax.swing.JButton estadisticasB;
    private javax.swing.JButton gestionInventarioB;
    private javax.swing.JButton gestionLocalB;
    private javax.swing.JButton gestionProductosB;
    private javax.swing.JButton ingresarB;
    private javax.swing.JToolBar menuToolBaar;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton pedidosB;
    // End of variables declaration//GEN-END:variables
}
