/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.BuscarProducto;
import Entidad.Producto;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author wilde
 */
public class GestionProductos extends javax.swing.JPanel {

    /**
     * Creates new form GestionProductos
     */
    public GestionProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriasDialog = new javax.swing.JDialog();
        PanelMostrarCategorias = new javax.swing.JPanel();
        panelBuscar = new javax.swing.JPanel();
        buscarProductosB = new javax.swing.JButton();
        buscarProductosTF = new javax.swing.JTextField();
        mostrarCategoriasB = new javax.swing.JButton();
        registrarCategoriaB = new javax.swing.JButton();
        registrarProductoB = new javax.swing.JButton();
        mostrarProductosSP = new javax.swing.JScrollPane();
        panelMostrarProductos = new javax.swing.JPanel();

        PanelMostrarCategorias.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout categoriasDialogLayout = new javax.swing.GroupLayout(categoriasDialog.getContentPane());
        categoriasDialog.getContentPane().setLayout(categoriasDialogLayout);
        categoriasDialogLayout.setHorizontalGroup(
            categoriasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMostrarCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        categoriasDialogLayout.setVerticalGroup(
            categoriasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMostrarCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buscarProductosB.setText("Buscar");
        buscarProductosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductosBActionPerformed(evt);
            }
        });

        buscarProductosTF.setText("producto");

        mostrarCategoriasB.setText("Categorías");

        registrarCategoriaB.setText("+");

        registrarProductoB.setText("+");

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarCategoriasB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarCategoriaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(registrarProductoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarProductosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarProductosB)
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarProductosB)
                    .addComponent(buscarProductosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarCategoriasB)
                    .addComponent(registrarCategoriaB)
                    .addComponent(registrarProductoB))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelMostrarProductos.setLayout(new java.awt.GridLayout());
        mostrarProductosSP.setViewportView(panelMostrarProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mostrarProductosSP)
                    .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarProductosSP, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProductosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductosBActionPerformed
        String busqueda = buscarProductosTF.getText();
        BuscarProducto buscar = new BuscarProducto();
        List<Producto> resultado = buscar.realizarBusqueda(busqueda);
        
        for(Producto p : resultado){
            ProductoPanel panelMostrar = new ProductoPanel();
            panelMostrar.getNombreL().setText(p.getNombreProducto());
            panelMostrar.getDescripcionL().setText(p.getDescripcion());
            panelMostrar.getPrecioL().setText(String.valueOf(p.getPrecio()));
            panelMostrarProductos.setVisible(false);
            panelMostrarProductos.add(panelMostrar);
            panelMostrarProductos.setVisible(true); 
        }
        
    }//GEN-LAST:event_buscarProductosBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMostrarCategorias;
    private javax.swing.JButton buscarProductosB;
    private javax.swing.JTextField buscarProductosTF;
    private javax.swing.JDialog categoriasDialog;
    private javax.swing.JButton mostrarCategoriasB;
    private javax.swing.JScrollPane mostrarProductosSP;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelMostrarProductos;
    private javax.swing.JButton registrarCategoriaB;
    private javax.swing.JButton registrarProductoB;
    // End of variables declaration//GEN-END:variables
}
