/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.AgregarCategoria;
import Control.AgregarProducto;
import Control.BuscarProducto;
import Control.ListarCategorias;
import Entidad.Categoria;
import Entidad.Producto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author wilde
 */
public class GestionProductos extends javax.swing.JPanel {

    /**
     * Creates new form GestionProductos
     */
    public GestionProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarProductoDialog = new javax.swing.JDialog();
        nombreL = new javax.swing.JLabel();
        descripcionL = new javax.swing.JLabel();
        precioL = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        descripcionTF = new javax.swing.JTextField();
        infoL = new javax.swing.JLabel();
        agregarB = new javax.swing.JButton();
        precioS = new javax.swing.JSpinner();
        panelBuscar = new javax.swing.JPanel();
        buscarProductosB = new javax.swing.JButton();
        buscarProductosTF = new javax.swing.JTextField();
        registrarCategoriaB = new javax.swing.JButton();
        registrarProductoB = new javax.swing.JButton();
        categoriasB = new javax.swing.JButton();
        mostrarSP = new javax.swing.JScrollPane();
        panelMostrar = new javax.swing.JPanel();

        agregarProductoDialog.setMinimumSize(new java.awt.Dimension(400, 216));

        nombreL.setText("Nombre");

        descripcionL.setText("Descripción");

        precioL.setText("Precio");

        infoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoL.setText("Ingrese los datos del nuevo producto");

        agregarB.setText("Agregar");
        agregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBActionPerformed(evt);
            }
        });

        precioS.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout agregarProductoDialogLayout = new javax.swing.GroupLayout(agregarProductoDialog.getContentPane());
        agregarProductoDialog.getContentPane().setLayout(agregarProductoDialogLayout);
        agregarProductoDialogLayout.setHorizontalGroup(
            agregarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarProductoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoL, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(agregarProductoDialogLayout.createSequentialGroup()
                        .addComponent(precioL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioS))
                    .addGroup(agregarProductoDialogLayout.createSequentialGroup()
                        .addComponent(descripcionL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcionTF))
                    .addGroup(agregarProductoDialogLayout.createSequentialGroup()
                        .addComponent(nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarProductoDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        agregarProductoDialogLayout.setVerticalGroup(
            agregarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarProductoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buscarProductosB.setText("Buscar");
        buscarProductosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductosBActionPerformed(evt);
            }
        });

        buscarProductosTF.setText("producto");

        registrarCategoriaB.setText("+");
        registrarCategoriaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCategoriaBActionPerformed(evt);
            }
        });

        registrarProductoB.setText("+");
        registrarProductoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoBActionPerformed(evt);
            }
        });

        categoriasB.setText("Categorias");
        categoriasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoriasB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarCategoriaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(registrarProductoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarProductosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarProductosB)
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarProductosB)
                    .addComponent(buscarProductosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarCategoriaB)
                    .addComponent(registrarProductoB)
                    .addComponent(categoriasB))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelMostrar.setLayout(new java.awt.GridLayout(1, 0));
        mostrarSP.setViewportView(panelMostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mostrarSP)
                    .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarSP, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProductosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductosBActionPerformed
        panelMostrar.setVisible(false);
        panelMostrar.removeAll();
        panelMostrar.setVisible(true);
        
        String busqueda = buscarProductosTF.getText();
        BuscarProducto buscar = new BuscarProducto();
        List<Producto> resultado = buscar.realizarBusqueda(busqueda);
        
        for(Producto p : resultado){
            ProductoPanel mostrar = new ProductoPanel(p);
            panelMostrar.setVisible(false);
            panelMostrar.add(mostrar);
            panelMostrar.setVisible(true); 
        }
    }//GEN-LAST:event_buscarProductosBActionPerformed

    private void registrarCategoriaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCategoriaBActionPerformed
        String nombreCategoria = JOptionPane.showInputDialog("Ingresa el nombre de la nueva categoria");
        Categoria nueva = new Categoria();
        nueva.setNombreCategoria(nombreCategoria);
        AgregarCategoria agregar = new AgregarCategoria();
        String resultado = agregar.validarAgregarCategoria(nueva);
        JOptionPane.showMessageDialog(this, resultado, "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_registrarCategoriaBActionPerformed

    private void registrarProductoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoBActionPerformed
        agregarProductoDialog.setVisible(true);
    }//GEN-LAST:event_registrarProductoBActionPerformed

    private void agregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBActionPerformed
        Producto nuevo = new Producto();
        nuevo.setNombreProducto(nombreTF.getText());
        nuevo.setDescripcion(descripcionTF.getText());
        nuevo.setPrecio((int) precioS.getValue());

        AgregarProducto agregar = new AgregarProducto();
        String resultado = agregar.validarAgregarProducto(nuevo);
        JOptionPane.showMessageDialog(this, resultado, "Información", JOptionPane.INFORMATION_MESSAGE);
        agregarProductoDialog.setVisible(false);
    }//GEN-LAST:event_agregarBActionPerformed

    private void categoriasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasBActionPerformed
        panelMostrar.setVisible(false);
        panelMostrar.removeAll();
        panelMostrar.setVisible(true);
        
        ListarCategorias listar = new ListarCategorias();
        List<Categoria> resultado = listar.validarLista();
        
        for(Categoria c : resultado){
            CategoriaPanel mostrar = new CategoriaPanel(c);
            panelMostrar.setVisible(false);
            panelMostrar.add(mostrar);
            panelMostrar.setVisible(true); 
        }
    }//GEN-LAST:event_categoriasBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarB;
    private javax.swing.JDialog agregarProductoDialog;
    private javax.swing.JButton buscarProductosB;
    private javax.swing.JTextField buscarProductosTF;
    private javax.swing.JButton categoriasB;
    private javax.swing.JLabel descripcionL;
    private javax.swing.JTextField descripcionTF;
    private javax.swing.JLabel infoL;
    private javax.swing.JScrollPane mostrarSP;
    private javax.swing.JLabel nombreL;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelMostrar;
    private javax.swing.JLabel precioL;
    private javax.swing.JSpinner precioS;
    private javax.swing.JButton registrarCategoriaB;
    private javax.swing.JButton registrarProductoB;
    // End of variables declaration//GEN-END:variables
}
