/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.BuscarProducto;
import Control.ModificarExistencias;
import DAO.ExistenciaDAO;
import Entidad.Existencia;
import Entidad.Producto;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author wilde
 */
public class GestionInventario extends javax.swing.JPanel {

    private ArrayList<ExistenciaPanel> existencias;
    
    /**
     * Creates new form GestionInventario
     */
    public GestionInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzarDiaB = new javax.swing.JButton();
        terminarDiaB = new javax.swing.JButton();
        aplicarB = new javax.swing.JButton();
        fechaL = new javax.swing.JLabel();
        mostrarExistenciasSP = new javax.swing.JScrollPane();
        mostrarExistenciasP = new javax.swing.JPanel();

        comenzarDiaB.setText("Comenzar dia");
        comenzarDiaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarDiaBActionPerformed(evt);
            }
        });

        terminarDiaB.setText("Terminar dia");
        terminarDiaB.setEnabled(false);
        terminarDiaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarDiaBActionPerformed(evt);
            }
        });

        aplicarB.setText("Aplicar");
        aplicarB.setEnabled(false);
        aplicarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarBActionPerformed(evt);
            }
        });

        fechaL.setText("Fecha");

        mostrarExistenciasP.setLayout(new java.awt.GridLayout(0, 1));
        mostrarExistenciasSP.setViewportView(mostrarExistenciasP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarExistenciasSP, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comenzarDiaB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                        .addComponent(terminarDiaB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fechaL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aplicarB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comenzarDiaB, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(terminarDiaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(mostrarExistenciasSP, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aplicarB, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(fechaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarBActionPerformed
        ModificarExistencias modificar = new ModificarExistencias();
        for(ExistenciaPanel p : existencias){
            Existencia nuevo = new Existencia();
            nuevo.setCantidad((int) p.getCantidadS().getValue());
            modificar.validarmodificarExistencias(p.getExistencia(), nuevo);
        }
    }//GEN-LAST:event_aplicarBActionPerformed

    private void terminarDiaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarDiaBActionPerformed
        comenzarDiaB.setEnabled(true);
        terminarDiaB.setEnabled(false);
        aplicarB.setEnabled(false);
    }//GEN-LAST:event_terminarDiaBActionPerformed

    private void comenzarDiaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarDiaBActionPerformed
        existencias = new ArrayList<>();
        Date hoy = new Date();
        BuscarProducto buscar = new BuscarProducto();
        ExistenciaDAO dao = new ExistenciaDAO();
        for(Producto p : buscar.realizarBusqueda("")){
            Existencia existencia = new Existencia();
            existencia.setFecha(hoy);
            existencia.setProducto(p);
            dao.crear(existencia);
        }
        for(Existencia e : dao.leer()){
            ExistenciaPanel mostrar = new ExistenciaPanel(e);
            mostrarExistenciasP.setVisible(false);
            mostrarExistenciasP.add(mostrar);
            existencias.add(mostrar);
            mostrarExistenciasP.setVisible(true);
        }
        comenzarDiaB.setEnabled(false);
        terminarDiaB.setEnabled(true);
        aplicarB.setEnabled(true);
    }//GEN-LAST:event_comenzarDiaBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarB;
    private javax.swing.JButton comenzarDiaB;
    private javax.swing.JLabel fechaL;
    private javax.swing.JPanel mostrarExistenciasP;
    private javax.swing.JScrollPane mostrarExistenciasSP;
    private javax.swing.JButton terminarDiaB;
    // End of variables declaration//GEN-END:variables
}
