/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.PedidoItem;
import javax.swing.JLabel;
import javax.swing.JSpinner;

/**
 *
 * @author wilde
 */
public class ItemPanel extends javax.swing.JPanel {

    PedidoItem item;
    
    
    /**
     * Creates new form ItemPanel
     * @param i
     */
    public ItemPanel(PedidoItem i) {
        initComponents();
        item = i;
        productoL.setText(i.getProducto().getNombreProducto());
        mostrarcuL.setText(String.valueOf(item.getProducto().getPrecio()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productoL = new javax.swing.JLabel();
        cuL = new javax.swing.JLabel();
        mostrarcuL = new javax.swing.JLabel();
        cantidadL = new javax.swing.JLabel();
        cantidadS = new javax.swing.JSpinner();
        subtotalL = new javax.swing.JLabel();
        mostrarSubtotalL = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(700, 54));

        productoL.setText("Producto");

        cuL.setText("C/U");

        mostrarcuL.setText("unidad");
        mostrarcuL.setMaximumSize(new java.awt.Dimension(100, 32));
        mostrarcuL.setMinimumSize(new java.awt.Dimension(100, 32));
        mostrarcuL.setPreferredSize(new java.awt.Dimension(100, 32));

        cantidadL.setText("Cantidad");
        cantidadL.setMaximumSize(new java.awt.Dimension(60, 32));
        cantidadL.setMinimumSize(new java.awt.Dimension(60, 32));
        cantidadL.setPreferredSize(new java.awt.Dimension(60, 32));

        cantidadS.setMaximumSize(new java.awt.Dimension(130, 32));
        cantidadS.setMinimumSize(new java.awt.Dimension(130, 32));
        cantidadS.setPreferredSize(new java.awt.Dimension(130, 32));

        subtotalL.setText("Subtotal");
        subtotalL.setMaximumSize(new java.awt.Dimension(80, 32));
        subtotalL.setMinimumSize(new java.awt.Dimension(80, 32));
        subtotalL.setPreferredSize(new java.awt.Dimension(80, 32));

        mostrarSubtotalL.setMaximumSize(new java.awt.Dimension(128, 32));
        mostrarSubtotalL.setMinimumSize(new java.awt.Dimension(128, 32));
        mostrarSubtotalL.setPreferredSize(new java.awt.Dimension(128, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productoL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarcuL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtotalL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarSubtotalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mostrarcuL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cuL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(subtotalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrarSubtotalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public PedidoItem getItem() {
        return item;
    }

    public void setItem(PedidoItem item) {
        this.item = item;
    }

    public JSpinner getCantidadS() {
        return cantidadS;
    }

    public void setCantidadS(JSpinner cantidadS) {
        this.cantidadS = cantidadS;
    }

    public JLabel getMostrarSubtotalL() {
        return mostrarSubtotalL;
    }

    public void setMostrarSubtotalL(JLabel mostrarSubtotalL) {
        this.mostrarSubtotalL = mostrarSubtotalL;
    }

    public JLabel getMostrarcuL() {
        return mostrarcuL;
    }

    public void setMostrarcuL(JLabel mostrarcuL) {
        this.mostrarcuL = mostrarcuL;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadL;
    private javax.swing.JSpinner cantidadS;
    private javax.swing.JLabel cuL;
    private javax.swing.JLabel mostrarSubtotalL;
    private javax.swing.JLabel mostrarcuL;
    private javax.swing.JLabel productoL;
    private javax.swing.JLabel subtotalL;
    // End of variables declaration//GEN-END:variables
}
