/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import javax.swing.JLabel;

/**
 *
 * @author wilde
 */
public class ProductoPanel extends javax.swing.JPanel {

    /**
     * Creates new form Producto
     */
    public ProductoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenL = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        descripcionL = new javax.swing.JLabel();
        precioL = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        imagenL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenL.setText("Imagen");
        imagenL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenLMouseClicked(evt);
            }
        });
        add(imagenL);

        nombreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreL.setText("Nombre");
        nombreL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreLMouseClicked(evt);
            }
        });
        add(nombreL);

        descripcionL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descripcionL.setText("Descripcion");
        descripcionL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descripcionLMouseClicked(evt);
            }
        });
        add(descripcionL);

        precioL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioL.setText("Precio");
        precioL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioLMouseClicked(evt);
            }
        });
        add(precioL);
    }// </editor-fold>//GEN-END:initComponents

    private void imagenLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenLMouseClicked
        
    }//GEN-LAST:event_imagenLMouseClicked

    private void nombreLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreLMouseClicked
        
    }//GEN-LAST:event_nombreLMouseClicked

    private void descripcionLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descripcionLMouseClicked
        
    }//GEN-LAST:event_descripcionLMouseClicked

    private void precioLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioLMouseClicked
        
    }//GEN-LAST:event_precioLMouseClicked

    private void modificarProducto(){
        
    }

    public JLabel getDescripcionL() {
        return descripcionL;
    }

    public void setDescripcionL(JLabel descripcionL) {
        this.descripcionL = descripcionL;
    }

    public JLabel getImagenL() {
        return imagenL;
    }

    public void setImagenL(JLabel imagenL) {
        this.imagenL = imagenL;
    }

    public JLabel getNombreL() {
        return nombreL;
    }

    public void setNombreL(JLabel nombreL) {
        this.nombreL = nombreL;
    }

    public JLabel getPrecioL() {
        return precioL;
    }

    public void setPrecioL(JLabel precioL) {
        this.precioL = precioL;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcionL;
    private javax.swing.JLabel imagenL;
    private javax.swing.JLabel nombreL;
    private javax.swing.JLabel precioL;
    // End of variables declaration//GEN-END:variables
}
