/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ModificarProducto;
import Entidad.Producto;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author wilde
 */
public class ProductoPanel extends javax.swing.JPanel {
    
    private Producto producto;

    /**
     * Creates new form Producto
     * @param p
     */
    public ProductoPanel(Producto p) {
        initComponents();
        producto = p;
        codigoMostrarL.setText(String.valueOf(p.getCodigoProducto()));
        nombreMostrarL.setText(p.getNombreProducto());
        descripcionMostrarL.setText(p.getDescripcion());
        precioMostrarL.setText(String.valueOf(p.getPrecio()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarProductoDialog = new javax.swing.JDialog();
        descripcionModificarL = new javax.swing.JLabel();
        precioModificarL = new javax.swing.JLabel();
        descripcionModificarTF = new javax.swing.JTextField();
        infoModificarL = new javax.swing.JLabel();
        modificarB = new javax.swing.JButton();
        precioModificarS = new javax.swing.JSpinner();
        codigoL = new javax.swing.JLabel();
        codigoMostrarL = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        nombreMostrarL = new javax.swing.JLabel();
        descripcionL = new javax.swing.JLabel();
        descripcionMostrarL = new javax.swing.JLabel();
        precioL = new javax.swing.JLabel();
        precioMostrarL = new javax.swing.JLabel();

        modificarProductoDialog.setMinimumSize(new java.awt.Dimension(400, 178));
        modificarProductoDialog.setName("Modificar Producto"); // NOI18N

        descripcionModificarL.setText("Descripción");

        precioModificarL.setText("Precio");

        infoModificarL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoModificarL.setText("Ingrese los datos a modificar del producto");

        modificarB.setText("Modificar");
        modificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBActionPerformed(evt);
            }
        });

        precioModificarS.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout modificarProductoDialogLayout = new javax.swing.GroupLayout(modificarProductoDialog.getContentPane());
        modificarProductoDialog.getContentPane().setLayout(modificarProductoDialogLayout);
        modificarProductoDialogLayout.setHorizontalGroup(
            modificarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoModificarL, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarProductoDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modificarB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarProductoDialogLayout.createSequentialGroup()
                        .addComponent(descripcionModificarL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcionModificarTF))
                    .addGroup(modificarProductoDialogLayout.createSequentialGroup()
                        .addComponent(precioModificarL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioModificarS)))
                .addContainerGap())
        );
        modificarProductoDialogLayout.setVerticalGroup(
            modificarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoModificarL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionModificarL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionModificarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modificarProductoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioModificarL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioModificarS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        codigoL.setText("Código:");
        add(codigoL);
        add(codigoMostrarL);

        nombreL.setText("Nombre:");
        nombreL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreLMouseClicked(evt);
            }
        });
        add(nombreL);

        nombreMostrarL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMostrarLMouseClicked(evt);
            }
        });
        add(nombreMostrarL);

        descripcionL.setText("Descripción:");
        descripcionL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descripcionLMouseClicked(evt);
            }
        });
        add(descripcionL);
        add(descripcionMostrarL);

        precioL.setText("Precio:");
        add(precioL);
        add(precioMostrarL);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreLMouseClicked
        modificarProducto();
    }//GEN-LAST:event_nombreLMouseClicked

    private void nombreMostrarLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMostrarLMouseClicked
        modificarProducto();
    }//GEN-LAST:event_nombreMostrarLMouseClicked

    private void descripcionLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descripcionLMouseClicked
        modificarProducto();
    }//GEN-LAST:event_descripcionLMouseClicked

    private void modificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBActionPerformed
        Producto nuevo = new Producto();
        nuevo.setDescripcion(descripcionModificarTF.getText());
        nuevo.setPrecio((int) precioModificarS.getValue());
        ModificarProducto modificar = new ModificarProducto();
        String resultado = modificar.validarModificarProducto(producto, nuevo);
        JOptionPane.showMessageDialog(this, resultado, "Información", JOptionPane.INFORMATION_MESSAGE);
        modificarProductoDialog.setVisible(false);
    }//GEN-LAST:event_modificarBActionPerformed

    private void modificarProducto(){
        modificarProductoDialog.setVisible(true);
    }

    public JLabel getDescripcionL() {
        return nombreMostrarL;
    }

    public void setDescripcionL(JLabel descripcionL) {
        this.nombreMostrarL = descripcionL;
    }

    public JLabel getNombreL() {
        return nombreL;
    }

    public void setNombreL(JLabel nombreL) {
        this.nombreL = nombreL;
    }

    public JLabel getPrecioL() {
        return descripcionL;
    }

    public void setPrecioL(JLabel precioL) {
        this.descripcionL = precioL;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoL;
    private javax.swing.JLabel codigoMostrarL;
    private javax.swing.JLabel descripcionL;
    private javax.swing.JLabel descripcionModificarL;
    private javax.swing.JTextField descripcionModificarTF;
    private javax.swing.JLabel descripcionMostrarL;
    private javax.swing.JLabel infoModificarL;
    private javax.swing.JButton modificarB;
    private javax.swing.JDialog modificarProductoDialog;
    private javax.swing.JLabel nombreL;
    private javax.swing.JLabel nombreMostrarL;
    private javax.swing.JLabel precioL;
    private javax.swing.JLabel precioModificarL;
    private javax.swing.JSpinner precioModificarS;
    private javax.swing.JLabel precioMostrarL;
    // End of variables declaration//GEN-END:variables
}
