/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.Categoria;

/**
 *
 * @author wilde
 */
public class CategoriaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoriaPanel
     * @param c
     */
    public CategoriaPanel(Categoria c) {
        initComponents();
        codigoMostrarL.setText(String.valueOf(c.getCodigoCategoria()));
        nombreMostrarL.setText(c.getNombreCategoria());;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigoL = new javax.swing.JLabel();
        codigoMostrarL = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        nombreMostrarL = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        codigoL.setText("Código:");
        jPanel1.add(codigoL);
        jPanel1.add(codigoMostrarL);

        nombreL.setText("Nombre:");
        jPanel1.add(nombreL);
        jPanel1.add(nombreMostrarL);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoL;
    private javax.swing.JLabel codigoMostrarL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreL;
    private javax.swing.JLabel nombreMostrarL;
    // End of variables declaration//GEN-END:variables
}
